export const FETCH_JOBS_REQUEST = '@@jobs/FETCH_JOBS_REQUEST';
export const FETCH_JOBS_SUCCESS = '@@jobs/FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_ERROR = '@@jobs/FETCH_JOBS_ERROR';
export const SELECTED_JOB_POSITION = '@@jobs/SELECTED_JOB_POSITION';